keywords: Hexo,HTML,CSS,JavaScript,FrontEnd,顾云翔,前端开发,顾云翔 个人博客
author: 顾云翔
description: 人生如逆旅，我亦是行人
# description: I ain't gonna be just a face in crowd.
avatar: https://avatars2.githubusercontent.com/u/7507079?v=3&s=460

twitter: guyunxiang
github: guyunxiang
weibo: guyunxing32

# Comment
duoshuo:
disqus:
gitalk:
  enable: true
  owner: guyunxiang
  admin: guyunxiang
  repo: guyunxiang.github.io
  ClientID: 8e90905eef1e8a7bfeb1
  ClientSecret: b119c52cd77840aaebcf3ab8d5ef129a3e1d4f6d

menu:
  home: /
  archives: /archives
  tags: /tags
  categories: /categories
  about: /about
  links: /links
